module Gobi
  VERSION: String
  # See the writing guide of rbs: https://github.com/ruby/rbs#guides
end

class String

  # traditional_gobi
  def deyansu: -> String
  def nari: -> String
  def degozaru: -> String

  # dialect_gobi
  def ja: -> String
  def dabe: -> String
end
