name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    
    - name: Run Test
      run: bundle exec rspec
    
    - name: Check Lint
      run: bundle exec rubocop
    
    - name: Check Type
      run: bundle exec steep check
